name: Update gist
on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: Fhwang0926/productive-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: b4fc6930552eba7ff730f4010fa5c61f
          TIMEZONE: Asia/Seoul
